.TH "src/config/config.cpp" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/config/config.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <streambuf>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <YACL/settings\&.h>\fP
.br
\fC#include <YACL/settings_ptr\&.h>\fP
.br
\fC#include <YACL/config\&.h>\fP
.br
\fC#include <helper/utils\&.h>\fP
.br
\fC#include <grammar/grammar\&.h>\fP
.br
\fC#include <type_conversation/converter\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
