.TH "examples/example5.cpp" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/example5.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <YACL/config\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBconfig_path\fP = CONFIG_PATH"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 6 of file example5\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const std::string config_path = CONFIG_PATH"

.PP
Definition at line 4 of file example5\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
