.TH "include/YACL/settings.h" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/YACL/settings.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <YACL/field\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fByacl::Setting\fP"
.br
.RI "YACL node class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fByacl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
