.TH "yacl::ContentTypeToType< ContentType::VECTOR_STRING_VALUE >" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yacl::ContentTypeToType< ContentType::VECTOR_STRING_VALUE > \- str_vector ContentType to real type converter  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types_conversation\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBstr_vector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct yacl::ContentTypeToType< ContentType::VECTOR_STRING_VALUE >"
str_vector ContentType to real type converter 
.PP
Definition at line 201 of file types_conversation\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fByacl::ContentTypeToType\fP< \fBContentType::VECTOR_STRING_VALUE\fP >::\fBtype\fP =  \fBstr_vector\fP"

.PP
Definition at line 202 of file types_conversation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
