.TH "yacl::ContentTypeToType< T >" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yacl::ContentTypeToType< T > \- Generic ContentType to real type converter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types_conversation\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<ContentType T>
.br
struct yacl::ContentTypeToType< T >"
Generic ContentType to real type converter\&. 
.PP
Definition at line 145 of file types_conversation\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<ContentType T> using \fByacl::ContentTypeToType\fP< T >::\fBtype\fP =  void"

.PP
Definition at line 146 of file types_conversation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
