.TH "yacl::YACLException" 3 "Wed Aug 22 2018" "YACL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yacl::YACLException \- YACL Exception class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception\&.h>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBYACLException\fP (const std::string &message)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SH "Detailed Description"
.PP 
YACL Exception class\&. 
.PP
Definition at line 10 of file exception\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "yacl::YACLException::YACLException (const std::string & message)\fC [inline]\fP"

.PP
Definition at line 12 of file exception\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "const char* yacl::YACLException::what () const\fC [inline]\fP, \fC [override]\fP, \fC [noexcept]\fP"

.PP
Definition at line 15 of file exception\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for YACL from the source code\&.
